name: Build, publish and deploy Docker image using GitHub Container Registry (GHCR) and Azure Container Apps

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: "ghcr.io"
      DOCKER_IMAGE: "fastapi-container"
      DOCKER_TAG: "${{ github.sha }}"
      AZURE_CONTAINER_APP_NAME: "ca-fastapi"
      AZURE_RESOURCE_GROUP: "rg-FastAPI-AzureContainerApp-dev"
      AZURE_MIN_REPLICAS: 1
      AZURE_MAX_REPLICAS: 5

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    # Checkout Repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Log in to GitHub Container Registry
    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Build and Push Docker image
    - name: Build and Docker image
      run: |
        docker build . -t ghcr.io/${{ github.repository }}/$DOCKER_IMAGE:$DOCKER_TAG
        docker push ghcr.io/${{ github.repository }}/$DOCKER_IMAGE:$DOCKER_TAG

    # Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Pull the Docker image from GHCR
    - name: Pull Docker image from GHCR
      run: |
        docker pull ghcr.io/${{ github.repository }}/$DOCKER_IMAGE:$DOCKER_TAG

    # Check if Azure CLI is installed
    - name: Check Azure CLI version
      run: az --version

    # Install Azure CLI Container Apps extension
    - name: Install Azure CLI Container Apps extension
      run: |
        az extension add --name containerapp --yes
        az extension list --query "[?name=='containerapp']"

    # Deploy to Azure Container Apps (ACA) from GHCR
    - name: Deploy to Azure Container Apps
      run: |
        az containerapp up \
        --name $AZURE_CONTAINER_APP_NAME \
        --resource-group $AZURE_RESOURCE_GROUP \
        --image $DOCKER_REGISTRY/${{ github.repository }}/$DOCKER_IMAGE:$DOCKER_TAG \
        --registry-server $DOCKER_REGISTRY \
        --registry-username ${{ github.actor }} \
        --registry-password ${{ secrets.GITHUB_TOKEN }} \
        --ingress external --target-port 8080
  
    # Set scaling parameters for Azure Container Apps (ACA)
    - name: Set scaling parameters for Azure Container Apps
      run: |
        az containerapp update \
        --name $AZURE_CONTAINER_APP_NAME \
        --resource-group $AZURE_RESOURCE_GROUP \
        --set scale.minReplicas=$AZURE_MIN_REPLICAS \
        --set scale.maxReplicas=$AZURE_MAX_REPLICAS

    # Show the deployed Azure Container App!
    - name: Verifiy Deployment
      run: |
        az containerapp show \
        --name $AZURE_CONTAINER_APP_NAME \
        --resource-group $AZURE_RESOURCE_GROUP \
        --query properties.configuration.ingress.fqdn
