name: Create and publish Docker Image CI for GitHub Container Registry

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: "fastapi-container"
      DOCKER_TAG: "latest"
      DOCKER_REGISTRY: "ghcr.io"

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build . -t ghcr.io/${{ github.repository }}/$DOCKER_IMAGE:$DOCKER_TAG

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}/$DOCKER_IMAGE:$DOCKER_TAG

    - name: Image digest
      run: docker inspect ghcr.io/${{ github.repository }}/$DOCKER_IMAGE:$DOCKER_TAG --format='{{index .RepoDigests 0}}'

    